### ISSUE TITLE
Problem at the module creation

### ISSUE THREAD

**Issue by alanschlindvein** [InfinitePress/generator-angular-package#1]
Look at this problem when I try to run 'yo angularjs-module'

![bug](https://cloud.githubusercontent.com/assets/185520/8253956/d1d8cdf2-166a-11e5-8d11-d25304c8c157.PNG)

This is happening just after I enter with my github username.

**Comment by coichedid** [comment]
Hi guy,

Thanks for your message.
I'm in vacations and I will be back next week.

As soon as I'm back, I will fix it.

Kindly,

Clovis Chedid

**Comment by alanschlindvein** [comment]
Thanks a lot man

**Comment by coichedid** [comment]
Hi Alan,

I think I figure out that issue.

For some reason, I really don't know, NPM Registry has an old version of
angular package generator.

I released another version, with correct package.

Pay attention on the name of the package when installing and using it. Its
name is "generator-angular-package". On old ReadMe.md, its name was
"generator-angularjs-module", so, the correct commands is:

npm -g install generator-angular-package

the to use it with:

yo angular-package

Or:
yo angular-package:directive <<directive name>>
Or:
yo angular-package:controller <<controller name>>
Or:
yo angular-package:service <<service name>>

Sorry for this mistake.

Best regards,
Clovis Chedid

On Mon, Jun 22, 2015 at 7:49 AM, alan schlindvein notifications@github.com
wrote:

> Closed #1
> https://github.com/InfinitePress/generator-angular-package/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/InfinitePress/generator-angular-package/issues/1#event-336581253
> .

## 

Clovis
