### ISSUE TITLE
is this project alive?

### ISSUE THREAD

**Issue by azachar** [InfinitePress/generator-angular-package#12]
Hey there,

is this project alive? There are 8 PR... 

Thanks,
Andrej

**Comment by lsiden** [comment]
Andrej, if InfinitePress no longer wants to continue maintaining this (or doesn't respond), I will be happy to work on this with you.

**Comment by azachar** [comment]
Hello @lsiden, 
Thank you for your response. Sure we can work out something together if InfinitePress do not have more time to work on this. 

I made couple of changes to generator-angular-package so I could use it for my own library.
I would be more then happy to share it back to the community. 

Cheers,
Andrej

**Comment by lsiden** [comment]
It doesn't look like IP is responding.  

Do you want to post your changes to me as pull-requests?  I'll vet them.  If they pass I'll merge them along with my own PR's that I originally sent to IP.

**Comment by coichedid** [comment]
Hi guys,

I'm so sorry for my disattention!

Those two last months were to much angry.

I will accept your PR now and reserve some time to get everything up to date.

Thanks a lot for your help, and if you like, I really would like to work with you.

Cheers Coichedid

**Comment by lsiden** [comment]
It looks like user coichedid of InfinitePress is merging my pull requests.  I wonder if our recent communication has prodded him a little.  So once he's done, maybe you can just fork his repo, then submit your PR's directly to him.  We may have to see and see if he intends to continue maintaining it.

**Comment by coichedid** [comment]
Guys, 

Just to confirm, this project is still alive and receiving new improvements.

I'll close this issue.
