### ISSUE TITLE
Want some enhancements

### ISSUE THREAD

**Issue by lsiden** [InfinitePress/generator-angular-package#3]
Major:
- Support template caching for templateUrl in directive $compile options.
- Support concatenation of stylesheets (.css and .scss) for directive modules.

Minor:
- Update README with instructions for testing.
- Add "license" field to bower.json and package.json
- Add "description" field to bower.json and package.json.
- Add "repository" field to bower.json and package.json.
- Prompt for description and gitUrl.
- Create example.html file to demo new component.

**Comment by lsiden** [comment]
Created pull request https://github.com/InfinitePress/generator-angular-package/pull/2 to support all the above.

**Comment by lsiden** [comment]
I understand I may have gotten over-ambitious.  Please let me know if you prefer that I break this into smaller PRs, each in it's own branch.

**Comment by coichedid** [comment]
Hi guy,

I did this component some time ago, just for me.
But I'm glad to see it is useful to someone else.
Feel free to pull requests as you prefer and I will analise those.

**Comment by lsiden** [comment]
Glad you responded.  I closed the PR b/c I realized that it wasn't complete yet.  I'll try to break it up into smaller PR's to make it easier for you to review.  Nice job, by the way!  This is just what I was looking for.

**Comment by lsiden** [comment]
There, I broke all that up into 8 smaller pull-requests which should be easier for you to process one by one.  Let me know if you need any help with anything.

**Comment by coichedid** [comment]
Hello Isiden,

I will analise your PR this weekend and give you some feedback.
